TempoHome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('profiles.urls', namespace='profiles')),
    url(r'', include('accommodation.urls', namespace='accommodation')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # helper function to return a URL pattern for serving files

accommodation/urls.py
from django.conf.urls import url
from . import views
from .views import (
    RoomList,
    RoomDetail,
    RoomDelete,
    RequestList,
    RequestUpdate
)

urlpatterns = [
    url(r'^account/dashboard$', views.dashboard, name="dashboard"),
    url(r'^account/rooms$', RoomList.as_view(), name='rooms_list'),
    url(r'^account/rooms/new$', views.create_room, name='new_room'),
    url(r'^account/room/(?P<pk>\d+)$', RoomDetail.as_view(), name='room_detail'),
    url(r'^account/room/delete/(?P<pk>\d+)$', RoomDelete.as_view(), name='room_delete'),
    url(r'^search', views.search, name="search"),
    url(r'^send-request', views.post_request, name="post_request"),
    url(r'^account/requests$', RequestList.as_view(), name='requests_list'),
    url(r'^account/requests/(?P<pk>\d+)/edit$', RequestUpdate.as_view(), name='request_edit'),
    url(r'^account/responses$', views.responses_list, name='responses_list'),
]

profiles/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^signup/$', views.sign_up, name="signup"),
    url(r'^login/$', views.authentication, name="login"),
    url(r'^logout$', auth_views.logout, {'next_page': '/'}, name="logout"),
    url(r'^account/profile/(?P<username>\w+)$', views.get_profile, name="get_profile")
]

accommodation/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Room(models.Model):
    address = models.CharField(max_length=150)
    description = models.CharField(max_length=200)
    rules = models.CharField(max_length=200, blank=True)
    user = models.ForeignKey(User)

class Picture(models.Model):
    picture = models.ImageField()
    room = models.ForeignKey(Room)

class Request(models.Model):
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    user = models.ForeignKey(User)
    room = models.ForeignKey(Room)
    STATUS_CHOICES = (
        ('P', 'Pending'),
        ('A', 'Approved'),
        ('R', 'Refused')
    )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='P')
    comments = models.CharField(max_length=250, blank=True)

accommodation/forms.py
from django.forms import ModelForm, TextInput, Select, Textarea, FileInput

from .models import Room, Picture, Request

class RoomForm(ModelForm):
    class Meta:
        model = Room
        exclude = ["user"]
        widgets = {
            'address': TextInput(attrs={'class': 'form-control form-control-danger', 'required': True}),
            'description': Textarea(attrs={'class': 'form-control form-control-danger', 'rows': 3, 'required': True}),
            'rules': Textarea(attrs={'class': 'form-control form-control-danger', 'rows': 3}),
        }

class PictureForm(ModelForm):
    class Meta:
        model = Picture
        fields = ["picture"]
        widgets = {
            'picture': FileInput(attrs={'class': 'form-control form-control-danger', 'accept': 'image/*', 'required': True}),
        }

class RequestForm(ModelForm):
    class Meta:
        model = Request
        fields = ['status', 'comments']
        widgets = {
            'status': Select(attrs={'class': 'form-control form-control-danger', 'required': True}),
            'comments': Textarea(attrs={'class': 'form-control form-control-danger', 'rows': 3})
        }

accommodation/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.forms import modelformset_factory
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView
from django.core.urlresolvers import reverse_lazy
from datetime import date
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Room, Picture, Request
from .forms import RoomForm, PictureForm, RequestForm

@login_required
def dashboard(request):
    return render(request, 'accommodation/dashboard.html')


@login_required
def create_room(request):
    # formsets allow the user to store several pictures at once
    PicureFormSet = modelformset_factory(Picture, form=PictureForm)

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request
        room_form = RoomForm(request.POST)
        picture_formset = PicureFormSet(request.POST, request.FILES, queryset=Picture.objects.none())

        # check whether it's valid
        if room_form.is_valid() and picture_formset.is_valid():
            new_room = room_form.save(commit=False)
            new_room.user = request.user
            new_room.save()

            for form in picture_formset.cleaned_data:
                picture = Picture(picture=form['picture'], room=new_room)
                picture.save()

            return HttpResponseRedirect('/account/rooms')

    # return blank forms
    else:
        room_form = RoomForm()
        picture_formset = PicureFormSet(queryset=Picture.objects.none())

    return render(request, 'accommodation/room_form.html', {'room_form': room_form, 'picture_formset': picture_formset})


@method_decorator(login_required, name='dispatch')

class RoomList(ListView):
   model = Room

   def get_queryset(self):
       user_rooms = Room.objects.filter(user=self.request.user)
       return user_rooms


@method_decorator(login_required, name='dispatch')
class RoomDetail(DetailView):
   model = Room


@method_decorator(login_required, name='dispatch')
class RoomDelete(DeleteView):
   model = Room
   success_url = reverse_lazy('accommodation:rooms_list')


# global variables
q = ''
room_list = ''
@login_required
def search(request):
   # check that 'q' exists in request.GET
   if 'q' in request.GET:
       global q # modify global copy of q
       q = request.GET.get('q')
       # get available rooms whose address contains q, without being case-sensitive.
       global room_list # modify global copy of room_list
       room_list = Room.objects.filter(address__icontains=q).exclude(user=request.user)
   else:
       global room_list  # modify global copy of room_list
       room_list = Room.objects.all()

   return render(request, 'accommodation/search_results.html', {'room_list': room_list, 'q': q})


@login_required
def post_request(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # room info
        room_id = request.POST.get('room')
        room = Room.objects.get(pk=room_id)

        # parse dates to required format for fields DateField typed
        daterange = request.POST.get('daterange')
        start_date, end_date = daterange.split("-")

        start_date = start_date.replace('/', '-')
        year, month, day = start_date.split("-")
        start_date = date(int(year), int(month), int(day))

        end_date = end_date.replace('/', '-')
        year, month, day = end_date.split("-")
        end_date = date(int(year), int(month), int(day))

        # save new request
        new_request = Request(start_date=start_date, end_date=end_date, user=request.user, room=room)
        new_request.save()

        message = "Your request sent successfully. Room's owner will get in touch with you as soon as possible"
        return render(request, 'accommodation/search_results.html', {'room_list': room_list, 'q': q, 'message': message, 'request': new_request})


@method_decorator(login_required, name='dispatch')
class RequestList(ListView):
   model = Request

   def get_queryset(self):
       user_requests = Request.objects.filter(room__user=self.request.user)
       return user_requests


@method_decorator(login_required, name='dispatch')
class RequestUpdate(UpdateView):
   model = Request
   success_url = reverse_lazy('accommodation:requests_list')
   form_class = RequestForm

@login_required
def responses_list(request):
   user_responses = Request.objects.filter(user=request.user)

   return render(request, 'accommodation/response_list.html', {'responses': user_responses})

templates/accommodation/dashboard.html
{% extends "base-dashboard.html" %}

{% load staticfiles %}

{% block title %}
    <title>Dashboard</title>
{% endblock %}

{% block nav %}
    <ul class="nav">
        <li class="active">
            <a href="{% url 'accommodation:dashboard' %}">
                <i class="ti-panel"></i>
                <p>Dashboard</p>
            </a>
        </li>
        <li>
            <a href="{% url 'accommodation:rooms_list' %}">
                <i class="glyphicon glyphicon-home"></i>
                <p>My Rooms</p>
            </a>
        </li>
        <li>
            <a href="{% url 'accommodation:requests_list' %}">
                <i class="glyphicon glyphicon-list"></i>
                <p>My Requests</p>
            </a>
        </li>
        <li>
            <a href="{% url 'accommodation:responses_list' %}">
                <i class="glyphicon glyphicon-bookmark"></i>
                <p>My responses</p>
            </a>
        </li>
        <li>
            <hr>
        </li>
        <li>
            <a href="{% url 'profiles:home' %}">
                <i class="glyphicon glyphicon-home"></i>
                <p>Home</p>
            </a>
        </li>
        <li>
            <a href="{% url 'profiles:get_profile' user.get_username %}">
                <i class="glyphicon glyphicon-user"></i>
                <p>Profile</p>
            </a>
        </li>
        <li>
            <a href="{% url 'profiles:logout' %}">
                <i class="glyphicon glyphicon-log-out"></i>
                <p>Logout</p>
            </a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-3 col-sm-6">
            <div class="card">
                <div class="content">
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="icon-big icon-warning text-center">
                                <i class="glyphicon glyphicon-home"></i>
                            </div>
                        </div>
                        <div class="col-xs-7">
                            <div class="numbers">
                                <p>Rooms</p>
                                4
                            </div>
                        </div>
                    </div>
                    <div class="footer">
                        <hr />
                        <div class="stats">
                            <i class="ti-reload"></i> Updated now
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card">
                <div class="content">
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="icon-big icon-success text-center">
                                <i class="glyphicon glyphicon-check"></i>
                            </div>
                        </div>
                        <div class="col-xs-7">
                            <div class="numbers">
                                <p>Requests</p>
                                3
                            </div>
                        </div>
                    </div>
                    <div class="footer">
                        <hr />
                        <div class="stats">
                            <i class="ti-reload"></i> Updated now
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card">
                <div class="content">
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="icon-big icon-danger text-center">
                                <i class="glyphicon glyphicon-user"></i>
                            </div>
                        </div>
                        <div class="col-xs-7">
                            <div class="numbers">
                                <p>Users</p>
                                8
                            </div>
                        </div>
                    </div>
                    <div class="footer">
                        <hr />
                        <div class="stats">
                            <i class="ti-reload"></i> Updated now
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">

        <div class="col-md-12">
            <div class="card">
                <div class="content">
                    <h3 class="text-center text-danger" style="font-family: 'Muli', 'Helvetica', Arial, sans-serif"><i class="glyphicon glyphicon-home"></i>&nbsp; Welcome to TempoHome, </h3>
                    <h4 class="text-center" style="font-weight: lighter">Temporary home for long-lasting friends!</h4>
                    <img class="img-rounded" src="{% static 'images/friends.jpeg' %}" alt="friends" width="350"
                         style="display: block; margin: 50px auto 40px;">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/accommodation/request_form.html
{% extends "base-dashboard.html" %}

{% load staticfiles %}

{% block title %}
    <title>Requests</title>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Requests</h4>
                    <p class="category">Update Request</p>
                </div>
                <div class="content">
                    <div class="form">
                        <form class="form-horizontal" method="post">
                            {% csrf_token %}

                            <div class="row">
                                <div class="col-md-6 col-md-push-3">
                                    {{ form.as_p }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-xs-12">
                                    <a type="button" class="btn btn-default pull-right" href="{% url 'accommodation:rooms_list' %}" style="margin-left: 10px"> Cancel </a>
                                    <button type="submit" class="btn btn-primary pull-right"> Save </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/accommodation/request_list.html
{% extends "base-dashboard.html" %}

{% load staticfiles %}

{% block title %}
    <title>Requests</title>
{% endblock %}

{% block nav %}
    <ul class="nav">
        <li>
            <a href="{% url 'accommodation:dashboard' %}">
                <i class="ti-panel"></i>
                <p>Dashboard</p>
            </a>
        </li>
        <li>
            <a href="{% url 'accommodation:rooms_list' %}">
                <i class="glyphicon glyphicon-home"></i>
                <p>My Rooms</p>
            </a>
        </li>
        <li class="active">
            <a href="{% url 'accommodation:requests_list' %}">
                <i class="glyphicon glyphicon-list"></i>
                <p>My Requests</p>
            </a>
        </li>
        <li>
            <a href="{% url 'accommodation:responses_list' %}">
                <i class="glyphicon glyphicon-bookmark"></i>
                <p>My responses</p>
            </a>
        </li>
        <li>
            <hr>
        </li>
        <li>
            <a href="{% url 'profiles:home' %}">
                <i class="glyphicon glyphicon-home"></i>
                <p>Home</p>
            </a>
        </li>
        <li>
            <a href="{% url 'profiles:get_profile' user.get_username %}">
                <i class="glyphicon glyphicon-user"></i>
                <p>Profile</p>
            </a>
        </li>
        <li>
            <a href="{% url 'profiles:logout' %}">
                <i class="glyphicon glyphicon-log-out"></i>
                <p>Logout</p>
            </a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Requests</h4>
                    <p class="category">Received Requests</p>
                </div>
                <div class="content">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <th>Address</th>
                                <th>Guest</th>
                                <th>From</th>
                                <th>To</th>
                                <th>Comments</th>
                            </thead>
                            <tbody>
                                {% for request in request_list %}
                                    <tr>
                                        <td class="col-md-4">
                                            <div class="col-md-3">
                                                {% if request.status == 'P' %}
                                                    <div class="img-circle status-red" data-toggle="tooltip" title="Pending">8</div>
                                                {% else %}
                                                    <div class="img-circle status-green" data-toggle="tooltip" title="Approved">8</div>
                                                {% endif %}

                                                <a class="btn-link" href="{% url 'accommodation:request_edit' request.id %}"><i class="glyphicon glyphicon-pencil"></i></a>
                                            </div>
                                            <div class="col-md-9">
                                                {{ request.room.address }}
                                            </div>
                                        </td>
                                        <td class="col-md-2">
                                            <a class="text-left" href="{% url 'profiles:get_profile' request.user %}"><i class="glyphicon glyphicon-user"></i> &nbsp; {{ request.user }}</a>
                                        </td>
                                        <td class="col-md-1">{{ request.start_date|date:"d/m/y" }}</td>
                                        <td class="col-md-1">{{ request.end_date|date:"d/m/y" }}</td>
                                        <td class="col-md-4">{{ request.comments }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
{% endblock %}

templates/accommodation/response_list.html
{% extends "base-dashboard.html" %}

{% load staticfiles %}

{% block title %}
    <title>Responses</title>
{% endblock %}

{% block nav %}
    <ul class="nav">
        <li>
            <a href="{% url 'accommodation:dashboard' %}">
                <i class="ti-panel"></i>
                <p>Dashboard</p>
            </a>
        </li>
        <li>
            <a href="{% url 'accommodation:rooms_list' %}">
                <i class="glyphicon glyphicon-home"></i>
                <p>My Rooms</p>
            </a>
        </li>
        <li>
            <a href="{% url 'accommodation:requests_list' %}">
                <i class="glyphicon glyphicon-list"></i>
                <p>My Requests</p>
            </a>
        </li>
        <li class="active">
            <a href="{% url 'accommodation:responses_list' %}">
                <i class="glyphicon glyphicon-bookmark"></i>
                <p>My responses</p>
            </a>
        </li>
        <li>
            <hr>
        </li>
        <li>
            <a href="{% url 'profiles:home' %}">
                <i class="glyphicon glyphicon-home"></i>
                <p>Home</p>
            </a>
        </li>
        <li>
            <a href="{% url 'profiles:get_profile' user.get_username %}">
                <i class="glyphicon glyphicon-user"></i>
                <p>Profile</p>
            </a>
        </li>
        <li>
            <a href="{% url 'profiles:logout' %}">
                <i class="glyphicon glyphicon-log-out"></i>
                <p>Logout</p>
            </a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Responses</h4>
                    <p class="category">Received Responses</p>
                </div>
                <div class="content">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <th>Address</th>
                                <th>From</th>
                                <th>To</th>
                                <th>Comments</th>
                            </thead>
                            <tbody>
                                {% for response in responses %}
                                    <tr>
                                        <td class="col-md-4">
                                            <div class="col-md-3">
                                                {% if response.status == 'P' %}
                                                    <div class="img-circle status-red" data-toggle="tooltip" title="Pending">8</div>
                                                {% else %}
                                                    <div class="img-circle status-green" data-toggle="tooltip" title="Approved">8</div>
                                                {% endif %}
                                            </div>
                                            <div class="col-md-9">
                                                {{ response.room.address }}
                                            </div>
                                        </td>
                                        <td class="col-md-1">{{ response.start_date|date:"d/m/y" }}</td>
                                        <td class="col-md-1">{{ response.end_date|date:"d/m/y" }}</td>
                                        <td class="col-md-4">{{ response.comments }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
{% endblock %}

templates/accommodation/room_detail.html
{% extends "base-dashboard.html" %}

{% load staticfiles %}

{% block title %}
    <title>Rooms</title>
{% endblock %}

{% block nav %}
    <ul class="nav">
        <li>
            <a href="{% url 'accommodation:dashboard' %}">
                <i class="ti-panel"></i>
                <p>Dashboard</p>
            </a>
        </li>
        <li class="active">
            <a href="{% url 'accommodation:rooms_list' %}">
                <i class="glyphicon glyphicon-home"></i>
                <p>My Rooms</p>
            </a>
        </li>
        <li>
            <a href="{% url 'accommodation:requests_list' %}">
                <i class="glyphicon glyphicon-list"></i>
                <p>My Requests</p>
            </a>
        </li>
        <li>
            <a href="{% url 'accommodation:responses_list' %}">
                <i class="glyphicon glyphicon-bookmark"></i>
                <p>My responses</p>
            </a>
        </li>
        <li>
            <hr>
        </li>
        <li>
            <a href="{% url 'profiles:home' %}">
                <i class="glyphicon glyphicon-home"></i>
                <p>Home</p>
            </a>
        </li>
        <li>
            <a href="{% url 'profiles:get_profile' user.get_username %}">
                <i class="glyphicon glyphicon-user"></i>
                <p>Profile</p>
            </a>
        </li>
        <li>
            <a href="{% url 'profiles:logout' %}">
                <i class="glyphicon glyphicon-log-out"></i>
                <p>Logout</p>
            </a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Room</h4>
                    <p class="category">Detailed info</p>
                </div>
                <div class="content">
                    <a href="{% url 'accommodation:rooms_list' %}" class="btn btn-primary">Back</a>

                    <br><br>

                    <p><strong>Address: </strong>{{ room.address }}</p>
                    <p><strong>Description: </strong>{{ room.description }}</p>
                    <p><strong>Rules: </strong>{{ room.rules }}</p>
                    <hr>

                    <h4 class="title">Room in pictures</h4>
                    <br>

                    <div class="row">
                        {% for picture in room.picture_set.all %}
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <img src="{{ picture.picture.url }}" alt="picture" width="200">
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/accommodation/room_list.html
{% extends "base-dashboard.html" %}

{% load staticfiles %}

{% block title %}
    <title>Rooms</title>
{% endblock %}

{% block nav %}
    <ul class="nav">
        <li>
            <a href="{% url 'accommodation:dashboard' %}">
                <i class="ti-panel"></i>
                <p>Dashboard</p>
            </a>
        </li>
        <li class="active">
            <a href="{% url 'accommodation:rooms_list' %}">
                <i class="glyphicon glyphicon-home"></i>
                <p>My Rooms</p>
            </a>
        </li>
        <li>
            <a href="{% url 'accommodation:requests_list' %}">
                <i class="glyphicon glyphicon-list"></i>
                <p>My Requests</p>
            </a>
        </li>
        <li>
            <a href="{% url 'accommodation:responses_list' %}">
                <i class="glyphicon glyphicon-bookmark"></i>
                <p>My responses</p>
            </a>
        </li>
        <li>
            <hr>
        </li>
        <li>
            <a href="{% url 'profiles:home' %}">
                <i class="glyphicon glyphicon-home"></i>
                <p>Home</p>
            </a>
        </li>
        <li>
            <a href="{% url 'profiles:get_profile' user.get_username %}">
                <i class="glyphicon glyphicon-user"></i>
                <p>Profile</p>
            </a>
        </li>
        <li>
            <a href="{% url 'profiles:logout' %}">
                <i class="glyphicon glyphicon-log-out"></i>
                <p>Logout</p>
            </a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Rooms</h4>
                    <p class="category">Saved Rooms</p>
                </div>
                <div class="content">
                    <a href="{% url 'accommodation:new_room' %}" class="btn btn-primary">Add New Room</a>

                    <br><br>

                    {% if room_list %}
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <th>Address</th>
                                </thead>
                                <tbody>
                                    {% for room in room_list %}
                                        <tr>
                                            <td>
                                                {{ room.address }}
                                            </td>

                                            <td>
                                               <a class="btn-link" href="{% url 'accommodation:room_detail' room.id %}"><i class="glyphicon glyphicon-eye-open"></i></a>
                                               <a class="btn-link" href="{% url 'accommodation:room_delete' room.id %}"><i class="glyphicon glyphicon-trash"></i></a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    {% else %}
                        <p>There are no stored rooms.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}