TempoHome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('profiles.urls', namespace='profiles')),
    url(r'', include('accommodation.urls', namespace='accommodation')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # helper function to return a URL pattern for serving files

accommodation/urls.py
from django.conf.urls import url
from . import views
from .views import (
    RoomList,
    RoomDetail,
    RoomDelete,
    RequestList,
    RequestUpdate
)

urlpatterns = [
    url(r'^account/dashboard$', views.dashboard, name="dashboard"),
    url(r'^account/rooms$', RoomList.as_view(), name='rooms_list'),
    url(r'^account/rooms/new$', views.create_room, name='new_room'),
    url(r'^account/room/(?P<pk>\d+)$', RoomDetail.as_view(), name='room_detail'),
    url(r'^account/room/delete/(?P<pk>\d+)$', RoomDelete.as_view(), name='room_delete'),
    url(r'^search', views.search, name="search"),
    url(r'^send-request', views.post_request, name="post_request"),
    url(r'^account/requests$', RequestList.as_view(), name='requests_list'),
    url(r'^account/requests/(?P<pk>\d+)/edit$', RequestUpdate.as_view(), name='request_edit'),
    url(r'^account/responses$', views.responses_list, name='responses_list'),
]

profiles/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^signup/$', views.sign_up, name="signup"),
    url(r'^login/$', views.authentication, name="login"),
    url(r'^logout$', auth_views.logout, {'next_page': '/'}, name="logout"),
    url(r'^account/profile/(?P<username>\w+)$', views.get_profile, name="get_profile")
]

profiles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    # auth related information about the user (username, password, email, first_name, last_name)
    # on_delete=models.CASCADE Automatically deletes related records when the related instance is removed
    user = models.OneToOneField(User, on_delete=models.CASCADE) # extend default Djando User model using a One-To-One Link

    # non-auth related information about the user
    picture = models.ImageField()
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')
    nationality = models.CharField(max_length=100)
    passport_number = models.CharField(max_length=20)
    passport_file = models.FileField()
    phone_number = models.CharField(max_length=20)
    description = models.CharField(max_length=200)
    college = models.CharField(max_length=230)

profiles/forms.py
from django.forms import ModelForm, TextInput, EmailInput, PasswordInput, FileInput, Select, Textarea

from .models import Profile
from django.contrib.auth.models import User

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "password", "first_name", "last_name"]
        widgets = {
            'username': TextInput(attrs={'class': 'form-control form-control-danger', 'required': True}),
            'email': EmailInput(attrs={'class': 'form-control form-control-danger', 'required': True}),
            'password': PasswordInput(attrs={'class': 'form-control form-control-danger', 'required': True}),
            'first_name': TextInput(attrs={'class': 'form-control form-control-danger', 'required': True}),
            'last_name': TextInput(attrs={'class': 'form-control form-control-danger', 'required': True}),
        }

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ["user"]
        widgets = {
            'gender': Select(attrs={'class': 'form-control form-control-danger', 'required': True}),
            'nationality': TextInput(attrs={'class': 'form-control form-control-danger', 'required': True}),
            'passport_number': TextInput(attrs={'class': 'form-control form-control-danger', 'required': True}),
            'passport_file': FileInput(attrs={'class': 'form-control form-control-danger', 'accept':'application/pdf image/*', 'required': True}),
            'phone_number': TextInput(attrs={'class': 'form-control form-control-danger', 'required': True}),
            'picture': FileInput(attrs={'class': 'form-control form-control-danger', 'accept': 'image/*', 'required': True}),
            'role': Select(attrs={'class': 'form-control form-control-danger', 'required': True}),
            'description': Textarea(attrs={'class': 'form-control form-control-danger', 'placeholder': 'Let us know your spoken languages, hobbies and related stuff about you', 'rows': 5, 'required': True}),
        }

profiles/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login

from .forms import *

def home(request):
    return render(request, 'profiles/home.html')


def sign_up(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)

        # check whether it's valid
        if user_form.is_valid() and profile_form.is_valid():
            # Create a new instance from the form's data
            new_user = user_form.save()
            # Form brings back a plain text string, not an encrypted password
            pw = new_user.password
            # Thus we need to use set password to encrypt the password string
            new_user.set_password(pw)
            # Save the new instance
            new_user.save()

            # Create, but don't save the new profile instance
            new_profile = profile_form.save(commit=False)
            # Set user field
            new_profile.user = new_user
            # Save new profile
            new_profile.save()

            # login new user
            username = user_form.cleaned_data.get('username')
            raw_password = user_form.cleaned_data.get('password')
            user = authenticate(username=username, password=raw_password)
            login(request, user)

            # redirect to a new URL:
            return HttpResponseRedirect('/account/dashboard')

    # if a GET (or any other method) we'll create a blank form
    else:
        user_form = UserForm()
        profile_form = ProfileForm()

    return render(request, 'profiles/sign_up.html', {'user_form': user_form, 'profile_form': profile_form})


def authentication(request):
    # redirect back if authenticated
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')

    if request.method == 'POST':
        # post data
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)

        # check if credentials match with a registered user
        user = authenticate(username=username, password=password)
        if user is not None:
            # correct username and password, so login the user
            login(request, user)
            # redirect to a success page
            return HttpResponseRedirect('/')
        else:
            # return an 'invalid login' error message
            message = 'Username and password were incorrect.'
            return render(request, 'profiles/login.html', {'message': message})

    return render(request, 'profiles/login.html', {})

def get_profile(request, username):
    user = User.objects.get(username=username)

    return render(request, 'profiles/profile.html', {'user': user})

templates/profiles/home.html
{% extends "base.html" %}

{% block title %}
    <title>Home</title>
{% endblock %}

{% block styles %}
    {% load staticfiles %}
    <!-- Home Style -->
	<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
    <header id="fh5co-header-section">
        <div class="container">
            <nav id="fh5co-menu-wrap" role="navigation">
                <ul class="sf-menu" id="fh5co-primary-menu">
                    <li><a href="">Home</a></li>
                    <li><a href="#fh5co-main">About us</a></li>
                    <li><a href="#fh5co-newsletter">Contact</a></li>
                    {% if user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-user"></span> 
                                <strong>Hi, {{ user.username }}</strong>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="row">
                                    <div class="col-sm-4">
                                        <img src="{{ user.profile.picture.url }}" alt="picture" width="60">
                                    </div>
                                    <div class="col-sm-8">
                                        <p><strong>{{ user.get_full_name }}</strong></p>
                                        <p>{{ user.email }}</p>
                                        <span><a href="{% url 'profiles:get_profile' user.get_username %}" class="profile text-danger"><i class="ti-settings"></i> &nbsp; Account</a></span>
                                    </div>
                                </li>
                                <li class="divider"></li>
                                <li><a href="{% url 'profiles:logout' %}" class="btn btn-danger logout"><i class="glyphicon glyphicon-log-out"></i> &nbsp; Logout</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
            </nav>

        </div>
    </header>

    <aside id="fh5co-hero">
        <div class="container">
            <div class="row">
                <div class="fh5co-hero-wrap">
                    <div class="fh5co-hero-intro">
                        <img class="img-responsive" style="margin: 60px auto 0" src="{% static 'images/logo.png' %}" alt="logo" width="450">
                        <br>
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-6 col-sm-offset-3">
                                    <div id="imaginary_container">
                                        <form class="form-horizontal" action="/search" method="get">
                                            <div class="input-group stylish-input-group">
                                                <input type="text" class="form-control input-lg" name="q" placeholder="Search by address ..." />
                                                <span class="input-group-addon">
                                                    <button type="submit">
                                                        <span class="glyphicon glyphicon-search"></span>
                                                    </button>
                                                </span>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br><br>

                        {% if not user.is_authenticated %}
                            <a href="{% url 'profiles:login' %}" class="btn btn-primary btn-lg">Log in</a>
                            <a href="{% url 'profiles:signup' %}" class="btn btn-default btn-lg">Sign up</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </aside>

    <div id="fh5co-main">
        <section id="fh5co-feature">
            <div class="container">
                <div class="row fh5co-feature-2">
                    <h2 class="fh5co-uppercase-heading-sm text-center">About us / Features</h2>
                    <p>TempoHome is a website designed to help foreign students finding a temporary place to stay while finding the best accommodation for a long run.</p>
                    <div class="fh5co-spacer fh5co-spacer-md"></div>
                    <div class="col-md-3 col-sm-6 fh5co-feature-item">
                        <span class="fh5co-feature-icon fh5co-circle"><i class="ti-gift"></i></span>
                        <h3 class="text-center fh5co-feature-title h4 text-uppercase">Free HTML5 Template</h3>
                        <p class="text-center fh5co-feature-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat aliquid placeat nobis veritatis neque earum possimus tempora sunt. </p>
                        <p class="text-center"><a href="#" class="btn btn-primary btn-sm">Read more</a></p>
                    </div>
                    <div class="col-md-3 col-sm-6 fh5co-feature-item">
                        <span class="fh5co-feature-icon fh5co-circle"><i class="ti-mobile"></i></span>
                        <h3 class="text-center fh5co-feature-title h4 text-uppercase">Mobile First</h3>
                        <p class="text-center fh5co-feature-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat aliquid placeat nobis veritatis neque earum possimus tempora sunt.</p>
                        <p class="text-center"><a href="#" class="btn btn-primary btn-sm">Read more</a></p>
                    </div>

                    <div class="clearfix visible-sm-block"></div>

                    <div class="col-md-3 col-sm-6 fh5co-feature-item">
                        <span class="fh5co-feature-icon fh5co-circle"><i class="ti-pie-chart"></i></span>
                        <h3 class="text-center fh5co-feature-title h4 text-uppercase">Analytics</h3>
                        <p class="text-center fh5co-feature-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat aliquid placeat nobis veritatis neque earum possimus tempora sunt.</p>
                        <p class="text-center"><a href="#" class="btn btn-primary btn-sm">Read more</a></p>
                    </div>
                    <div class="col-md-3 col-sm-6 fh5co-feature-item">
                        <span class="fh5co-feature-icon fh5co-circle"><i class="ti-wallet"></i></span>
                        <h3 class="text-center fh5co-feature-title h4 text-uppercase">Increase Income</h3>
                        <p class="text-center fh5co-feature-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat aliquid placeat nobis veritatis neque earum possimus tempora sunt.</p>
                        <p class="text-center"><a href="#" class="btn btn-primary btn-sm">Read more</a></p>
                    </div>
                </div>
            </div>
        </section>

        <section id="fh5co-newsletter">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 text-center">
                        <h2 class="fh5co-uppercase-heading-sm fh5co-no-margin-bottom">Subscribe Newsletter</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, assumenda.</p>
                        <div class="fh5co-spacer fh5co-spacer-xxs"></div>
                        <form method="post" action="#">
                          <div class="form-group">
                            <label for="email" class="sr-only">Email address</label>
                            <input type="email" class="form-control input-lg" id="email" placeholder="Email">
                          </div>
                          <input type="submit" class="btn btn-primary btn-lg btn-block" value="Send">
                        </form>
                    </div>
                </div>
            </div>
        </section>

        <footer id="fh5co-footer">
            <div class="container">
                <ul class="fh5co-social-icons">
                    <li><a href="#"><i class="ti-twitter-alt"></i></a></li>
                    <li><a href="#"><i class="ti-facebook"></i></a></li>
                    <li><a href="#"><i class="ti-github"></i></a></li>
                    <li><a href="#"><i class="ti-linkedin"></i></a></li>
                </ul>
                <p class="text-muted fh5co-no-margin-bottom text-center"><small>&copy; 2015 <a href="#">Display</a>. All rights reserved. Crafted with love <em>by</em> <a href="http://freehtml5.co" target="_blank">FREEHTML5.co</a> <br> Images by <a href="http://unsplash.com/" target="_blank">Unsplash</a></small></p>
            </div>
        </footer>
    </div>
{% endblock %}

templates/profiles/login.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}
    <title>Log in</title>
{% endblock %}

{% block styles %}
    <!-- Auth Style -->
	<link rel="stylesheet" href="{% static 'css/auth.css' %}">
    <style>
        .login-container {
            width: 40%;
        }

        @media screen and (max-width: 767px) {
            .login-container {
                width: 90%;
            }
        }

        @media screen and (min-width: 768px) and (max-width: 991px) {
            .login-container {
                width: 60%;
            }
        }
    </style>
{% endblock %}

{% block content %}
    <div class="login-container">
        <div class="row">
            <img class="img-responsive" src="{% static 'images/logo.png' %}" alt="logo" width="280">
            <h3 class="text-center">Log in to TempoHome</h3>
            <p class="text-center"> Need an account? <a href="{% url 'profiles:signup' %}"> &nbsp; Sign up here</a></p>
        </div>

        <div class="form-box">
            <form class="form-horizontal" method="post">
                {% csrf_token %}

                {% if message %}
                    <p class="text-danger text-center"><strong>{{ message }}</strong></p>
                {% endif %}

                <div class="row">
                    <div class="form-group {% if message %}has-error has-feedback{% endif %}">
                        <label class="control-label col-xs-10 col-xs-push-1 col-sm-3" for="id_username"><label for="id_username">Username:</label></label>
                        <div class="col-xs-10 col-xs-push-1 col-sm-8">
                            <input class="form-control" id="id_username" maxlength="30" name="username" type="text" required="">
                        </div>
                    </div>

                    <div class="form-group {% if message %}has-error has-feedback{% endif %}">
                        <label class="control-label col-xs-10 col-xs-push-1 col-sm-3" for="id_password"><label for="id_password">Password:</label></label>
                        <div class="col-xs-10 col-xs-push-1 col-sm-8">
                            <input class="form-control" id="id_password" maxlength="128" name="password" type="password" required="">
                        </div>
                    </div>
                </div>

                <br>

                <div class="row">
                    <a type="button" class="btn btn-default pull-right" href="{% url 'profiles:home' %}"> Cancel </a>
                    <button type="submit" class="btn btn-primary pull-right"> Get in </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/profiles/profile.html
{% extends "base-dashboard.html" %}

{% load staticfiles %}

{% block title %}
    <title>Profile</title>
{% endblock %}

{% block styles %}
    <style>
        /**
         * Profile image component
         */
        .profile-header-container{
            margin: 0 auto;
        }

        .profile-header-img {
            padding: 84px 54px 10px;
        }

        .profile-header-img > img.img-circle {
            width: 210px;
            height: 210px;
            border: 3px solid #d75d30;
        }

    </style>
{% endblock %}

{% block nav %}
    <ul class="nav">
        <li>
            <a href="{% url 'accommodation:dashboard' %}">
                <i class="ti-panel"></i>
                <p>Dashboard</p>
            </a>
        </li>
        <li>
            <a href="{% url 'accommodation:rooms_list' %}">
                <i class="glyphicon glyphicon-home"></i>
                <p>My Rooms</p>
            </a>
        </li>
        <li>
            <a href="{% url 'accommodation:requests_list' %}">
                <i class="glyphicon glyphicon-list"></i>
                <p>My Requests</p>
            </a>
        </li>
        <li>
            <a href="{% url 'accommodation:responses_list' %}">
                <i class="glyphicon glyphicon-bookmark"></i>
                <p>My responses</p>
            </a>
        </li>
        <li>
            <hr>
        </li>
        <li>
            <a href="{% url 'profiles:home' %}">
                <i class="glyphicon glyphicon-home"></i>
                <p>Home</p>
            </a>
        </li>
        <li class="active">
            <a href="{% url 'profiles:get_profile' user.get_username %}">
                <i class="glyphicon glyphicon-user"></i>
                <p>Profile</p>
            </a>
        </li>
        <li>
            <a href="{% url 'profiles:logout' %}">
                <i class="glyphicon glyphicon-log-out"></i>
                <p>Logout</p>
            </a>
        </li>
    </ul>
{% endblock %}


{% block content %}
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="content">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="profile-header-container">
                                        <div class="profile-header-img">
                                            <img class="img-circle" src="{{ user.profile.picture.url }}" >
                                        </div>
                                        <h3 class="text-center"><strong>{{ user.get_full_name }}</strong></h3>
                                        <p class="text-center">{{ user.username }}</p>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <h5>Contact info</h5>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Phone Number</label>
                                                <input type="text" class="form-control border-input" disabled value="{{ user.profile.phone_number }}">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Email address</label>
                                                <input type="email" class="form-control border-input" disabled value="{{ user.email }}">
                                            </div>
                                        </div>
                                    </div>

                                    <hr>

                                    <h5>Other relevant info</h5>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Gender</label>
                                                <input type="text" class="form-control border-input" disabled value="{{ user.profile.get_gender_display }}">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Nationality</label>
                                                <input type="text" class="form-control border-input" disabled value="{{ user.profile.nationality }}">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Passport Number</label>
                                                <input type="text" class="form-control border-input" disabled value="{{ user.profile.passport_number }}">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Passport File</label>
                                                <br>
                                                <a class="btn-link btn-block text-danger" href="{{ user.profile.passport_file.url }}" target="_blank">Open file</a>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>About Me</label>
                                                <textarea rows="4" class="form-control border-input">{{ user.profile.description }}</textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <a type="button" class="btn btn-primary pull-right" href="{% url 'accommodation:requests_list' %}"> Back </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/profiles/sign_up.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}
    <title>Sign up</title>
{% endblock %}

{% block styles %}
    <!-- Auth Style -->
	<link rel="stylesheet" href="{% static 'css/auth.css' %}">
    <style>
        .login-container {
            width: 90%;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="login-container">
        <div class="row">
            <img class="img-responsive" src="{% static 'images/logo.png' %}" alt="logo" width="280">
            <h3 class="text-center">Create a New Account</h3>
            <p class="text-center">Come and join TempoHome community!. Let's set up your account. Already have one? <a href="{% url 'profiles:login' %}"> &nbsp; Log in here</a></p>
        </div>

        <div class="form-box">
            <form class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="row">
                    {% for field in user_form %}
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group {% if field.errors %}has-error has-feedback{% endif %}">
                                <label class="control-label col-sm-4" for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                                <div class="col-sm-8">
                                    {{ field }}
                                    <small class="text-danger"> {{ field.errors }} </small>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                    {% for field in profile_form %}
                        <div class="col-xs-12 col-md-6">
                            <div class="form-group {% if field.errors %}has-error has-feedback{% endif %}">
                                <label class="control-label col-sm-4" for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                                <div class="col-sm-8">
                                    {{ field }}
                                    <small class="text-danger"> {{ field.errors }} </small>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <div class="row">
                    <a type="button" class="btn btn-default pull-right" href="{% url 'profiles:home' %}"> Cancel </a>
                    <button type="submit" class="btn btn-primary pull-right"> Sign up </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}